### ISSUE TITLE
One question about Troponin I

### ISSUE THREAD

**Issue by Xyz723** [vitaldb/examples#2]
Hello, I have a question. In the lab data, I can't find 'Troponin I' in the column 'name'. As far as I know, there is not any abbreviation in the column 'name'  that means 'Troponin I'. Can you give me any information about how the 'Troponin I' comes from. Thank you!

**Comment by vitaldb** [comment]
The troponin values were removed from this version.
We will include the data when we release the next version.
Sorry for your inconvenience.

Hyung-Chul Lee

**Comment by Xyz723** [comment]
Thank you for your reply. Looking forward to the release of the next version.
